name: DDD

on:
    workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install selenium requests futures eventlet

      - name: Run itv
        run: python ${{ github.workspace }}/py/itv.py

      - name: Run cctv
        run: python ${{ github.workspace }}/py/cctv.py
                
      - name: Run weishi
        run: python ${{ github.workspace }}/py/weishi.py
                
      - name: Run qita
        run: python ${{ github.workspace }}/py/qita.py

      - name: 提交更改
        run: |
          git config --local user.email "csszue@gmail.com"  # 设置 Git 用户邮箱
          git config --local user.name "MemoryCollection"  # 设置 Git 用户名
          cp tv/itvlist.txt ./  # 将 tv/itvlist.txt 文件复制到根目录
          git add tv/*  # 添加 tv/ 目录下的所有文件
          git add itvlist.txt  # 添加根目录下的 itvlist.txt 文件
          git commit -m "Copy itvlist.txt to root directory and add generated files to TV directory"
          #git pull --rebase
          git push -f

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/iptv
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}


          
          
          
          

          